services:
  postgres:
    image: postgres:15
    container_name: postgres_ticket_db
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_project2:/var/lib/postgresql/data

volumes:
  pgdata_project2:
